### ISSUE TITLE
LiquidCrystal_I2C

### ISSUE THREAD

**Issue by albertusgeyser** [ZivaVatra/ArduLCD#2]
Good Day

Could you help to add I2C to your arduino coding to allow me to use i2c Module on Arduino?
I tried using: 
// LiquidCrystal_I2C.h: https://github.com/johnrickman/LiquidCrystal_I2C
But not much luck yet.

Thank You

Albertus Geyser

**Comment by ZivaVatra** [comment]
Hi Albertus, Any luck?

Unfortunately as I don't have an I2C module I can't test/debug this myself, so I am of limited use here.

**Comment by ZivaVatra** [comment]
Closing due to lack of response.
